services:
  postgres:
    image: postgres:16
    container_name: notes_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notesdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  notesapi:
    image: notesapi_image
    build:
      context: .
      dockerfile: NotesApi/Dockerfile
    container_name: notes_api
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=notesdb;Username=postgres;Password=postgres"
    ports:
      - "5000:8080"

  redis:
    image: redis:8
    container_name: notes_redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
